edition = "2024"
unstable_features = false
tab_spaces = 2
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
normalize_comments = true
wrap_comments = true
comment_width = 80
max_width = 100
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 50
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
trailing_semicolon = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
type_punctuation_density = "Wide"
control_brace_style = "AlwaysSameLine"
brace_style = "PreferSameLine"
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_try_shorthand = true
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 20
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
overflow_delimited_expr = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
