import { defineConfig } from 'oxfmt';

export default defineConfig({
  ignorePatterns: [
    '.github/**',
    'AGENTS.md',
    'README.md',
    'dist',
    'node_modules',
    'bun.lock',
    'package.json',
    'lefthook.yaml',
    'index.html',
    'public/**/*.html',
    'messages/**/*.json',
    'i18n.inlang/**/*.json',
    'src/styles.css',
    'src-tauri/**/*.json',
    'tsconfig*.json',
    '**/*.tsbuildinfo',
    '**/*.toml',
    '**/autoImports.d.ts',
    '**/paraglide/**',
    '**/*.gen.ts',
    'src-tauri/target/**',
    'src-tauri/gen/**',
    'src-yolo/**',
  ],
  singleQuote: true,
  jsxSingleQuote: true,
  sortImports: {
    groups: [
      'type-import',
      ['value-builtin', 'value-external'],
      'type-internal',
      'value-internal',
      ['type-parent', 'type-sibling', 'type-index'],
      ['value-parent', 'value-sibling', 'value-index'],
      'unknown',
    ],
  },
  sortTailwindcss: {
    stylesheet: './src/styles.css',
    functions: ['tv', 'cn', 'cx', 'cnMerge'],
    preserveWhitespace: true,
  },
  sortPackageJson: {
    sortScripts: true,
  },
});
