/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsKeyboardIndexRouteImport } from './routes/settings/keyboard/index'
import { Route as SettingsGamepadIndexRouteImport } from './routes/settings/gamepad/index'
import { Route as SettingsDebugIndexRouteImport } from './routes/settings/debug/index'
import { Route as SettingsAppearanceIndexRouteImport } from './routes/settings/appearance/index'
import { Route as SettingsAppConnectionIndexRouteImport } from './routes/settings/app-connection/index'
import { Route as SettingsRovSystemIndexRouteImport } from './routes/settings/rov/system/index'
import { Route as SettingsRovRegulatorIndexRouteImport } from './routes/settings/rov/regulator/index'
import { Route as SettingsRovPowerIndexRouteImport } from './routes/settings/rov/power/index'
import { Route as SettingsRovConnectionIndexRouteImport } from './routes/settings/rov/connection/index'
import { Route as SettingsRovCalibrationIndexRouteImport } from './routes/settings/rov/calibration/index'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsKeyboardIndexRoute = SettingsKeyboardIndexRouteImport.update({
  id: '/keyboard/',
  path: '/keyboard/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsGamepadIndexRoute = SettingsGamepadIndexRouteImport.update({
  id: '/gamepad/',
  path: '/gamepad/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDebugIndexRoute = SettingsDebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceIndexRoute = SettingsAppearanceIndexRouteImport.update({
  id: '/appearance/',
  path: '/appearance/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppConnectionIndexRoute =
  SettingsAppConnectionIndexRouteImport.update({
    id: '/app-connection/',
    path: '/app-connection/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsRovSystemIndexRoute = SettingsRovSystemIndexRouteImport.update({
  id: '/rov/system/',
  path: '/rov/system/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRovRegulatorIndexRoute =
  SettingsRovRegulatorIndexRouteImport.update({
    id: '/rov/regulator/',
    path: '/rov/regulator/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsRovPowerIndexRoute = SettingsRovPowerIndexRouteImport.update({
  id: '/rov/power/',
  path: '/rov/power/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRovConnectionIndexRoute =
  SettingsRovConnectionIndexRouteImport.update({
    id: '/rov/connection/',
    path: '/rov/connection/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsRovCalibrationIndexRoute =
  SettingsRovCalibrationIndexRouteImport.update({
    id: '/rov/calibration/',
    path: '/rov/calibration/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/settings/app-connection/': typeof SettingsAppConnectionIndexRoute
  '/settings/appearance/': typeof SettingsAppearanceIndexRoute
  '/settings/debug/': typeof SettingsDebugIndexRoute
  '/settings/gamepad/': typeof SettingsGamepadIndexRoute
  '/settings/keyboard/': typeof SettingsKeyboardIndexRoute
  '/settings/rov/calibration/': typeof SettingsRovCalibrationIndexRoute
  '/settings/rov/connection/': typeof SettingsRovConnectionIndexRoute
  '/settings/rov/power/': typeof SettingsRovPowerIndexRoute
  '/settings/rov/regulator/': typeof SettingsRovRegulatorIndexRoute
  '/settings/rov/system/': typeof SettingsRovSystemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/app-connection': typeof SettingsAppConnectionIndexRoute
  '/settings/appearance': typeof SettingsAppearanceIndexRoute
  '/settings/debug': typeof SettingsDebugIndexRoute
  '/settings/gamepad': typeof SettingsGamepadIndexRoute
  '/settings/keyboard': typeof SettingsKeyboardIndexRoute
  '/settings/rov/calibration': typeof SettingsRovCalibrationIndexRoute
  '/settings/rov/connection': typeof SettingsRovConnectionIndexRoute
  '/settings/rov/power': typeof SettingsRovPowerIndexRoute
  '/settings/rov/regulator': typeof SettingsRovRegulatorIndexRoute
  '/settings/rov/system': typeof SettingsRovSystemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/settings/app-connection/': typeof SettingsAppConnectionIndexRoute
  '/settings/appearance/': typeof SettingsAppearanceIndexRoute
  '/settings/debug/': typeof SettingsDebugIndexRoute
  '/settings/gamepad/': typeof SettingsGamepadIndexRoute
  '/settings/keyboard/': typeof SettingsKeyboardIndexRoute
  '/settings/rov/calibration/': typeof SettingsRovCalibrationIndexRoute
  '/settings/rov/connection/': typeof SettingsRovConnectionIndexRoute
  '/settings/rov/power/': typeof SettingsRovPowerIndexRoute
  '/settings/rov/regulator/': typeof SettingsRovRegulatorIndexRoute
  '/settings/rov/system/': typeof SettingsRovSystemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/'
    | '/settings/app-connection/'
    | '/settings/appearance/'
    | '/settings/debug/'
    | '/settings/gamepad/'
    | '/settings/keyboard/'
    | '/settings/rov/calibration/'
    | '/settings/rov/connection/'
    | '/settings/rov/power/'
    | '/settings/rov/regulator/'
    | '/settings/rov/system/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/app-connection'
    | '/settings/appearance'
    | '/settings/debug'
    | '/settings/gamepad'
    | '/settings/keyboard'
    | '/settings/rov/calibration'
    | '/settings/rov/connection'
    | '/settings/rov/power'
    | '/settings/rov/regulator'
    | '/settings/rov/system'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/'
    | '/settings/app-connection/'
    | '/settings/appearance/'
    | '/settings/debug/'
    | '/settings/gamepad/'
    | '/settings/keyboard/'
    | '/settings/rov/calibration/'
    | '/settings/rov/connection/'
    | '/settings/rov/power/'
    | '/settings/rov/regulator/'
    | '/settings/rov/system/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/keyboard/': {
      id: '/settings/keyboard/'
      path: '/keyboard'
      fullPath: '/settings/keyboard/'
      preLoaderRoute: typeof SettingsKeyboardIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/gamepad/': {
      id: '/settings/gamepad/'
      path: '/gamepad'
      fullPath: '/settings/gamepad/'
      preLoaderRoute: typeof SettingsGamepadIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/debug/': {
      id: '/settings/debug/'
      path: '/debug'
      fullPath: '/settings/debug/'
      preLoaderRoute: typeof SettingsDebugIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance/': {
      id: '/settings/appearance/'
      path: '/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof SettingsAppearanceIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/app-connection/': {
      id: '/settings/app-connection/'
      path: '/app-connection'
      fullPath: '/settings/app-connection/'
      preLoaderRoute: typeof SettingsAppConnectionIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/rov/system/': {
      id: '/settings/rov/system/'
      path: '/rov/system'
      fullPath: '/settings/rov/system/'
      preLoaderRoute: typeof SettingsRovSystemIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/rov/regulator/': {
      id: '/settings/rov/regulator/'
      path: '/rov/regulator'
      fullPath: '/settings/rov/regulator/'
      preLoaderRoute: typeof SettingsRovRegulatorIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/rov/power/': {
      id: '/settings/rov/power/'
      path: '/rov/power'
      fullPath: '/settings/rov/power/'
      preLoaderRoute: typeof SettingsRovPowerIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/rov/connection/': {
      id: '/settings/rov/connection/'
      path: '/rov/connection'
      fullPath: '/settings/rov/connection/'
      preLoaderRoute: typeof SettingsRovConnectionIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/rov/calibration/': {
      id: '/settings/rov/calibration/'
      path: '/rov/calibration'
      fullPath: '/settings/rov/calibration/'
      preLoaderRoute: typeof SettingsRovCalibrationIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAppConnectionIndexRoute: typeof SettingsAppConnectionIndexRoute
  SettingsAppearanceIndexRoute: typeof SettingsAppearanceIndexRoute
  SettingsDebugIndexRoute: typeof SettingsDebugIndexRoute
  SettingsGamepadIndexRoute: typeof SettingsGamepadIndexRoute
  SettingsKeyboardIndexRoute: typeof SettingsKeyboardIndexRoute
  SettingsRovCalibrationIndexRoute: typeof SettingsRovCalibrationIndexRoute
  SettingsRovConnectionIndexRoute: typeof SettingsRovConnectionIndexRoute
  SettingsRovPowerIndexRoute: typeof SettingsRovPowerIndexRoute
  SettingsRovRegulatorIndexRoute: typeof SettingsRovRegulatorIndexRoute
  SettingsRovSystemIndexRoute: typeof SettingsRovSystemIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAppConnectionIndexRoute: SettingsAppConnectionIndexRoute,
  SettingsAppearanceIndexRoute: SettingsAppearanceIndexRoute,
  SettingsDebugIndexRoute: SettingsDebugIndexRoute,
  SettingsGamepadIndexRoute: SettingsGamepadIndexRoute,
  SettingsKeyboardIndexRoute: SettingsKeyboardIndexRoute,
  SettingsRovCalibrationIndexRoute: SettingsRovCalibrationIndexRoute,
  SettingsRovConnectionIndexRoute: SettingsRovConnectionIndexRoute,
  SettingsRovPowerIndexRoute: SettingsRovPowerIndexRoute,
  SettingsRovRegulatorIndexRoute: SettingsRovRegulatorIndexRoute,
  SettingsRovSystemIndexRoute: SettingsRovSystemIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
